/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package JCurrencyConverter;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.util.HashMap;
import java.util.Map;

/**
 *
 * @author athar
 */
public class JCurrencyConverter extends javax.swing.JFrame {

    /**
     * Creates new form JCurrencyConverter
     */
    public JCurrencyConverter() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtxtAmount = new javax.swing.JTextField();
        jToCurrency = new javax.swing.JComboBox<>();
        jFromCurrency = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jtxtAmountConverted = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jbtnExit = new javax.swing.JButton();
        jbtnConverter = new javax.swing.JButton();
        jbtnReset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 20));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 48)); // NOI18N
        jLabel1.setText("Currency Converter");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, 450, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 950, 120));

        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 255, 204), 20, true));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 153, 51));
        jLabel5.setText("Amount");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 140, 50));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 153, 51));
        jLabel6.setText("From Currency");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 260, 40));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 153, 51));
        jLabel4.setText("To Currency");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 250, -1));

        jtxtAmount.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jPanel2.add(jtxtAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, 560, 40));

        jToCurrency.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jToCurrency.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "GBP - Britain", "CAD - Canadian Dollar", "NGN - Nigerian Dollar", "MXN - Mexcan Peso", "EUR - Euro", "CHF - Swiss Franc", "AUD - Australian", "CNY - Chinese Yuan", "INR - Indian Rupee", "USD - United States Dollar", "PKR - Paskitani Rupee", "JPY - Japanese Yen", "TBH - Thai Baht", "VND - Vietnamese Dong", "AED - United Arab Emirates Dirham", "ZMK- Zambian Kwacha", "HDK - Hong Kong Dollar", "NZD - New Zealand Dollar" }));
        jPanel2.add(jToCurrency, new org.netbeans.lib.awtextra.AbsoluteConstraints(325, 130, -1, 40));

        jFromCurrency.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jFromCurrency.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "GBP - Britain", "CAD - Canadian Dollar", "NGN - Nigerian Dollar", "MXN - Mexcan Peso", "EUR - Euro", "CHF - Swiss Franc", "AUD - Australian", "CNY - Chinese Yuan", "INR - Indian Rupee", "USD - United States Dollar", "PKR - Paskitani Rupee", "JPY - Japanese Yen", "TBH - Thai Baht", "VND - Vietnamese Dong", "AED - United Arab Emirates Dirham", "ZMK -Zambian Kwacha", "HDK - Hong Kong Dollar", "NZD - New Zealand Dollar" }));
        jPanel2.add(jFromCurrency, new org.netbeans.lib.awtextra.AbsoluteConstraints(325, 80, -1, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 950, 200));

        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 255, 204), 20, true));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 102));
        jLabel2.setText("Amount Converted");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));
        jLabel2.getAccessibleContext().setAccessibleParent(jLabel1);

        jtxtAmountConverted.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jPanel3.add(jtxtAmountConverted, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, 550, 40));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 950, 110));
        jPanel3.getAccessibleContext().setAccessibleParent(jLabel1);

        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 204), 20, true));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtnExit.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnExit.setText("Exit");
        jbtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnExitActionPerformed(evt);
            }
        });
        jPanel4.add(jbtnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 30, 290, 50));

        jbtnConverter.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnConverter.setText("Converter");
        jbtnConverter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnConverterActionPerformed(evt);
            }
        });
        jPanel4.add(jbtnConverter, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 270, 50));

        jbtnReset.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnReset.setText("Reset");
        jbtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnResetActionPerformed(evt);
            }
        });
        jPanel4.add(jbtnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, 290, 50));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 950, 110));

        pack();
    }// </editor-fold>//GEN-END:initComponents
private JFrame frame;
    private void jbtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnExitActionPerformed
      frame = new JFrame("Exit");
      
      if (JOptionPane.showConfirmDialog(frame, "Confirm if you want to exit","Currency Converter",
            JOptionPane.YES_NO_OPTION )  == JOptionPane.YES_NO_OPTION)
            {
                System.exit(0);
  }
    }//GEN-LAST:event_jbtnExitActionPerformed

    private void jbtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnResetActionPerformed
       
        jtxtAmount.setText("");
        jtxtAmountConverted.setText("");
        jFromCurrency.setSelectedIndex(-1);
        jToCurrency.setSelectedIndex(-1);
    }//GEN-LAST:event_jbtnResetActionPerformed

    private void jbtnConverterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnConverterActionPerformed
        double amount;
        String fromcurrency;
        String tocurrency;
        double convertAmount;
        try
        {
            amount = Double.parseDouble(jtxtAmount.getText());    
        }catch (NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Please enter a vaild number","Exclamation", JOptionPane.ERROR_MESSAGE);
            jtxtAmount.setText("");
            jtxtAmount.requestFocus();
            return;
    }//GEN-LAST:event_jbtnConverterActionPerformed
    fromcurrency = jFromCurrency.getSelectedItem().toString().substring(0,3);
     tocurrency = jToCurrency.getSelectedItem().toString().substring(0,3);
     
     convertAmount = convertCurrency(amount ,fromcurrency,tocurrency);
     
     jtxtAmountConverted.setText(amount + " " + fromcurrency+ " = " + convertAmount + " " + tocurrency);
            }         
    
    //==================================================================================
    public double convertCurrency(double amount,String fromcurrency,String tocurrency)
    {
        Map<String ,Double> conversionRate = new HashMap<>();
        conversionRate.put("GBP",1.0);
        conversionRate.put("CAD",1.86);
        conversionRate.put("NGN",2014.31);
        conversionRate.put("MXN",26.07);
        conversionRate.put("EUR",1.19);
        conversionRate.put("CHF",1.14);
        conversionRate.put("AUD",2.05);
        conversionRate.put("CNY",9.40);
        conversionRate.put("INR",112.11);
        conversionRate.put("USD",1.30);
        conversionRate.put("PKR",364.00);
        conversionRate.put("JPY",193.00);
        conversionRate.put("TBH",43.65);
        conversionRate.put("VND",33203.00);
        conversionRate.put("AED",4.77);
        conversionRate.put("ZMK",37.40);
        conversionRate.put("HDK",10.11);
        conversionRate.put("NZD",2.24);
        
      if(!conversionRate.containsKey(fromcurrency)||!conversionRate.containsKey(tocurrency)) {
          throw new IllegalArgumentException("Invalid currency code .");
      }
      return amount * conversionRate.get(tocurrency)/ conversionRate.get(fromcurrency);
    }
    //==================================================================================
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JCurrencyConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JCurrencyConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JCurrencyConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JCurrencyConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
 
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new JCurrencyConverter().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jFromCurrency;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JComboBox<String> jToCurrency;
    private javax.swing.JButton jbtnConverter;
    private javax.swing.JButton jbtnExit;
    private javax.swing.JButton jbtnReset;
    private javax.swing.JTextField jtxtAmount;
    private javax.swing.JTextField jtxtAmountConverted;
    // End of variables declaration//GEN-END:variables
}